apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-sample
spec:
  version: v3.5.21
  size: 3
